# -- general
# prefix
unbind C-b
set -g prefix 'C-Space' # 设置全局前缀

# 鼠标支持
set -g mouse on
# 开启键盘扩展（比如上下左右按键）
set -s extended-keys on
set -as terminal-features 'kitty*:extkeys'

set -s focus-events on

# 增加Buffer容量,扩展到10000行
# set -g history-limit 10000

# 编号显示从1开始
set -g base-index 1
setw -g pane-base-index 1

# 窗口重命名
setw -g automatic-rename on
set -g renumber-windows on

# 终端标题设置
set -g set-titles on
set -g set-titles-string "#S:#W"

# 提示时长设置
# set -g display-time 2000
set -g display-panes-time 2000

# 时间设定
set -sg repeat-time 300
# set -s escape-time 0 # 在tmux-sensible插件中包含

# session and window的生命周期管理
set -sg exit-empty on # 最后一个session关闭，tmux自动中断进程
set -g detach-on-destroy off
set -g allow-passthrough on

# set default shell
set -g default-shell /usr/bin/zsh

# notification and warning
set -g visual-activity off
set -g monitor-bell off

# environment
set -ga update-environment '\
QT_IM_MODULE QT_QPA_PLATFORMTHEME \
SESSION_MANAGER \
XDG_CONFIG_HOME XDG_CACHE_HOME XDG_DATA_HOME\
XDG_MENU_PREFIX XDG_RUNTIME_DIR XDG_SESSION_CLASS \
XDG_SESSION_DESKTOP XDG_SESSION_TYPE XDG_CURRENT_DESKTOP \
XMODIFIERS \
FZF_DEFAULT_OPTS \
TMUX_THEME_COLOR \
TERM TERM_PROGRAM \
'

# --session
# ctrl A (prefix) + 大写C创建一个新的session
bind C command-prompt -p "new session name: " "new -s '%%'"

# -- windows

# -- pane
bind | split-window -h # 垂直分割当前窗口
bind _ split-window -v # 水平分割当前窗口

# 真彩支持
set -g default-terminal "tmux-256color"
set -as terminal-features ",*256col*:RGB"
# set -as terminal-overrides ",*256col*:Tc"
# set-option -ga terminal-overrides ",xterm-kitty:Tc"
# set-option -ga terminal-overrides ",*256color*:Tc"

# -- plugins, TPM tmux plugin manager
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark' # or 'dark256', 'light', 'light256'
set -g @plugin 'T1erno/tmux-auto-renumber-session'
# 关机后也可以实现session持久化
set -g @plugin 'tmux-plugins/tmux-resurrect' # 注意：该插件可以仅保存系统重启后的布局
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-save-interval '15'  # 每 15 分钟自动保存一次
set -g @continuum-restore 'on'        # 启动 tmux 时自动恢复

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
